spring.application.name=leetcode-tracker

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.forward-headers-strategy=framework

leetcode-graphql.base-url=https://leetcode.com/graphql

cors.allowed-origins=https://yousefelghoul.gitlab.io
cors.allowed-origin-patterns=http://localhost:*
