spring.application.name=leetcode-tracker

server.forward-headers-strategy=framework

leetcode-graphql.base-url=https://leetcode.com/graphql
cors.allowed-origins=https://yousefelghoul.gitlab.io
cors.allowed-origin-patterns=http://localhost:*
