CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS heatmap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    visited BOOLEAN NOT NULL DEFAULT FALSE,
    solved BOOLEAN NOT NULL DEFAULT FALSE,
    total_solved INTEGER,
    CONSTRAINT uk_heatmap_username_date UNIQUE (username, date)
);

CREATE INDEX IF NOT EXISTS idx_heatmap_username_date ON heatmap (username, date);

ALTER TABLE users ALTER COLUMN password TYPE VARCHAR(255);
ALTER TABLE heatmap ALTER COLUMN total_solved DROP NOT NULL;
